//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3082
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NetEmailer {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class NetEmailer {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal NetEmailer() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NetEmailer.NetEmailer", typeof(NetEmailer).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}&quot; cannot be empty..
        /// </summary>
        internal static string Argument_Cannot_Be_Empty {
            get {
                return ResourceManager.GetString("Argument_Cannot_Be_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File with the name {0} is not found..
        /// </summary>
        internal static string File_Not_Found {
            get {
                return ResourceManager.GetString("File_Not_Found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid boolean attribute {0}..
        /// </summary>
        internal static string Invalid_Bool_Attr {
            get {
                return ResourceManager.GetString("Invalid_Bool_Attr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid integer attribute {0}..
        /// </summary>
        internal static string Invalid_Integer_Attr {
            get {
                return ResourceManager.GetString("Invalid_Integer_Attr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid positive integer attribute {0}..
        /// </summary>
        internal static string Invalid_Positive_Integer_Attr {
            get {
                return ResourceManager.GetString("Invalid_Positive_Integer_Attr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid type attribute {0}..
        /// </summary>
        internal static string Invalid_Type_Attr {
            get {
                return ResourceManager.GetString("Invalid_Type_Attr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No child nodes..
        /// </summary>
        internal static string No_Child_Nodes {
            get {
                return ResourceManager.GetString("No_Child_Nodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Node {0} missing required attribute {1}..
        /// </summary>
        internal static string Node_Missing_Required_Attr {
            get {
                return ResourceManager.GetString("Node_Missing_Required_Attr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Node type is not element..
        /// </summary>
        internal static string Node_Type_Is_Not_Element {
            get {
                return ResourceManager.GetString("Node_Type_Is_Not_Element", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required attribute {0} can not be empty..
        /// </summary>
        internal static string Required_Attr_Can_Not_Be_Empty {
            get {
                return ResourceManager.GetString("Required_Attr_Can_Not_Be_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required attribute {0} is missing..
        /// </summary>
        internal static string Required_Attr_Missing {
            get {
                return ResourceManager.GetString("Required_Attr_Missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unrecognized_attribute {0}..
        /// </summary>
        internal static string Unrecognized_Attr {
            get {
                return ResourceManager.GetString("Unrecognized_Attr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unrecognized element..
        /// </summary>
        internal static string Unrecognized_Element {
            get {
                return ResourceManager.GetString("Unrecognized_Element", resourceCulture);
            }
        }
    }
}
